["ascii_forever.txt"]
name = "ASCII Forever logo"
created_at = 2021-05-26
hidden = true

["ascii_forever_iso.txt"]
name = "ASCII Forever logo experiment"
created_at = 2021-06-18

["chains.txt"]
name = "Chains"
created_at = 2021-06-15

["data_apis.txt"]
name = "Data APIs logo"
created_at = 2021-08-31
hidden = true

["godot.txt"]
name = "Godot logo"
created_at = 2018-08-08

["hammer_sickle.txt"]
name = "Hammer and Sickle"
created_at = 2021-06-19
hidden = true

["honno_iso.txt"]
name = "Isometric font experiment"
created_at = 2017-11-28

["hypothesis.txt"]
name = "Hypothesis logo"
created_at = 2021-05-30

["iso_experiment.txt"]
name = "Waveland"
created_at = 2021-07-19
hidden = true

["ninja.txt"]
name = "Ninja"
created_at = 2021-06-07

["python.txt"]
name = "Python logo"
created_at = 2021-07-06

["python_big.txt"]
name = "Python logo"
created_at = 2020-08-23
hidden = true

["rich.txt"]
name = "Rich logo (original by dew)"
created_at = 2021-08-21